name: An idea
description: Something Falak could do.
labels: ["idea"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like, and when would you use it?
    validations:
      required: true
